version: '3.8'
services:
  db-mysql:
    image: mysql:8
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: sandbox-mysql
      MYSQL_USER: sandbox-mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - db-sandbox-mysql:/var/lib/mysql
  db-postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sandbox-postgres
    ports:
      - '5433:5432'
    volumes:
      - db-sandbox-postgres:/var/lib/postgresql/data
  db-mssql:
    build:
      context: ./images/mssql-customize
      dockerfile: Dockerfile
    ports:
      - '1434:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
      - SA_PASSWORD=Password123
volumes:
  db-sandbox-mysql:
    driver: local
  db-sandbox-postgres:
    driver: local
